name: aitl-cli
base: core22
version: '0.2.0'
summary: A CLI client for Azure Image Testing for Linux API
description: |
  The AITL client is a light CLI client for the Azure Image Testing for Linux API

license: GPL-3.0
contact: cpc@canonical.com
website: https://github.com/canonical/aitl-cli
issues: https://github.com/canonical/aitl-cli/issues

grade: stable
confinement: strict

parts:
  aitl-cli:
    plugin: python
    source: .
    python-packages:
      - pip
      - setuptools
      - wheel
      - '.'

apps:
  aitl-cli:
    command: bin/aitl-cli
    plugs:
      - network
