name: penguinator-cli
base: core22
version: '0.1'
summary: A CLI client for Azure's Penguinator API
description: |
  The penguinator API provide an abstraction on top of LISA which is a tool
  for testing Linux VMs on different clouds (Azure, AWS, libvirt...)

grade: stable
confinement: strict

parts:
  penguinator-cli:
    plugin: python
    source: .
    python-packages:
      - pip
      - setuptools
      - wheel
      - '.'

apps:
  penguinator-cli:
    command: bin/penguinator-cli
    plugs:
      - network
